rvm: '2.2.1'

addons:
  code_climate:
    repo_token: 77a755f2d5a93dc952a8f540b3c4ca819296a0834066ec5f7ff144f9338021d1

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: bundle exec rspec spec
script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec
